### ISSUE TITLE
Issue with Twist msg and rosserial

### ISSUE THREAD

**Issue by eliaskrchnr** [2788west/cerusbot#1]
Hi, 
I fail to set up a subscriber on my Arduino that listens to Twist commands from /cmd_vel.
Other messages and topics work.
I took your arduino code and boiled it down to a minimum. Every time my arduino gets a Twist command, the LED should blink.
But nothing happens.
Du you have any idea, what Im doing wrong? I use ubuntu 20 and ROS noetic on my laptop.
Here is my code:
```
#include <ros.h>
#include <geometry_msgs/Twist.h>

//Configure ROS
ros::NodeHandle nh;
geometry_msgs::Twist msg;

//Create a message callback that updates the motor speeds
void messageCb(const geometry_msgs::Twist& cmd_vel)
{
    digitalWrite(5, HIGH-digitalRead(5)); 
}

//Subscribe to the Twist message
ros::Subscriber <geometry_msgs::Twist> sub("/cmd_vel", &messageCb);

//Setup the node and subscriber once
void setup()
{
    nh.initNode();
    nh.subscribe(sub);
    pinMode(5, OUTPUT);
    digitalWrite(5, HIGH);
    Serial.begin(9600); // needs to be at end of setup loop
}

//Loop forever
void loop()
{
  while (!nh.connected())
  {
    nh.spinOnce();
  }
    nh.spinOnce();
    delay(1);
}
```

Im really glad for any hint!
Regards!

**Comment by 2788west** [comment]
Dear @eliaskrchnr,

I'm not using rosserial for Arduino for this repo because I think it was giving me some issues. Instead, my Arduino implementation is ROS-free and just receives messages from the Jetson Nano that are then being parsed into move commands.

Looking at your code, I would make sure that:

1. Your ROS master is running and accessible from the Arduino
2. Calling `digitalWrite(5, HIGH-digitalRead(5));` with a 1 ms spin time will flash the LED so fast you won't be able to see it. I'd add a print statement to the callback function to debug it.
3. Make sure your ROS topics and message names match exactly. You can use `rostopic list` and `rostopic echo /cmd_vel` in your ROS environment to check.

I hope this helps!

**Comment by 2788west** [comment]
Hi @eliaskrchnr,

Thanks for your question. The code in the repo has been tested and should be working, but depending on your ROS version and other differences there may be issues. Here are a few suggestions:

1. Make sure that the ROS master is running and accessible to the Arduino.
2. I would add a print statement to you callback message to ensure it's actually being called. Using `digitalWrite(5, HIGH-digitalRead(5));` with a 1ms spin time will blink the LED so fast that it probably won't be visible.
3. Make sure your topics and messages are actually being broadcast by checking `rostopic list` and `rostopic echo /cmd_vel`

I hope this helps!
